-- Client identity: a person is identified by CPF and may hold one client account per establishment.
--   person                : identity only (CPF, digits only). Contact data stays on each account so an
--                           establishment never sees what another establishment recorded.
--   client (the account)  : keeps its id, so purchase.client_id keeps pointing at the same rows.
-- Also adds establishment groups with an opt-in flag for sharing clients inside the group.
-- Valid on both PostgreSQL and H2. If a legacy client has no CPF or two legacy clients of the SAME
-- establishment share a CPF once punctuation is removed, this migration fails on purpose: fix the data first.

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cpf VARCHAR(11) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (cpf)
);

INSERT INTO person (cpf)
SELECT DISTINCT REPLACE(REPLACE(REPLACE(cpf, '.', ''), '-', ''), ' ', '') FROM client;

ALTER TABLE client ADD COLUMN person_id BIGINT;
UPDATE client SET person_id = (
    SELECT p.id FROM person p
    WHERE p.cpf = REPLACE(REPLACE(REPLACE(client.cpf, '.', ''), '-', ''), ' ', '')
);
ALTER TABLE client ALTER COLUMN person_id SET NOT NULL;
ALTER TABLE client ADD CONSTRAINT fk_client_person FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE client ADD CONSTRAINT uq_client_person_establishment UNIQUE (person_id, establishment_id);

-- The CPF now lives only on person (dropping the column also drops its old unique constraint)
ALTER TABLE client DROP COLUMN cpf;

ALTER TABLE client ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE client ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

CREATE TABLE establishment_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE establishment ADD COLUMN group_id BIGINT;
ALTER TABLE establishment ADD COLUMN share_clients BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE establishment ADD CONSTRAINT fk_establishment_group FOREIGN KEY (group_id) REFERENCES establishment_group(id);
CREATE INDEX idx_establishment_group ON establishment (group_id);
