-- Points ledger, purchase date/discount data, reward catalog, redemptions and per-establishment reward settings.
-- Valid on both PostgreSQL and H2.

-- ---- purchase: date, discount, points bookkeeping, cancellation
ALTER TABLE purchase ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE purchase ADD COLUMN discount_amount DECIMAL(19,2) DEFAULT 0 NOT NULL;
ALTER TABLE purchase ADD COLUMN points_redeemed INT DEFAULT 0 NOT NULL;
ALTER TABLE purchase ADD COLUMN points_earned INT DEFAULT 0 NOT NULL;
ALTER TABLE purchase ADD COLUMN cancelled_at TIMESTAMP;

-- Points already granted by existing purchases: floor(amount / value_per_point), the documented rule
UPDATE purchase SET points_earned = (
    SELECT CAST(FLOOR(purchase.amount / e.value_per_point) AS INT)
    FROM establishment e WHERE e.id = purchase.establishment_id
);

-- ---- establishment: how points pay off
ALTER TABLE establishment ADD COLUMN reward_mode VARCHAR(20) DEFAULT 'CATALOG' NOT NULL;
ALTER TABLE establishment ADD COLUMN points_to_currency_rate DECIMAL(10,4) DEFAULT 0.1000 NOT NULL;
ALTER TABLE establishment ADD COLUMN max_discount_percent INT DEFAULT 50 NOT NULL;
ALTER TABLE establishment ADD CONSTRAINT chk_establishment_reward_mode CHECK (reward_mode IN ('CATALOG', 'DISCOUNT', 'CASHBACK'));
ALTER TABLE establishment ADD CONSTRAINT chk_establishment_rate CHECK (points_to_currency_rate > 0);
ALTER TABLE establishment ADD CONSTRAINT chk_establishment_max_discount CHECK (max_discount_percent BETWEEN 1 AND 100);

-- ---- reward catalog
CREATE TABLE reward (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    establishment_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    type VARCHAR(20) NOT NULL,
    points_cost INT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    stock INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (establishment_id) REFERENCES establishment(id),
    CONSTRAINT chk_reward_type CHECK (type IN ('BRINDE', 'CUPOM')),
    CONSTRAINT chk_reward_points_cost CHECK (points_cost > 0),
    CONSTRAINT chk_reward_stock CHECK (stock IS NULL OR stock >= 0)
);
CREATE INDEX idx_reward_establishment ON reward (establishment_id);

-- ---- points ledger (append-only): client.points is always the sum of its entries
CREATE TABLE points_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    client_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    points INT NOT NULL,
    balance_after INT NOT NULL,
    purchase_id BIGINT,
    reward_id BIGINT,
    reason VARCHAR(255),
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES client(id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(purchase_id),
    FOREIGN KEY (reward_id) REFERENCES reward(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT chk_ledger_type CHECK (type IN ('CREDIT', 'REDEEM', 'ADJUST', 'REVERSAL')),
    CONSTRAINT chk_ledger_points CHECK (points <> 0),
    CONSTRAINT chk_ledger_balance CHECK (balance_after >= 0)
);
CREATE INDEX idx_ledger_client ON points_ledger (client_id, id);

-- Backfill: one CREDIT per existing purchase that granted points, with the running balance
INSERT INTO points_ledger (client_id, type, points, balance_after, purchase_id, reason)
SELECT client_id, 'CREDIT', points_earned,
       SUM(points_earned) OVER (PARTITION BY client_id ORDER BY purchase_id),
       purchase_id, 'Purchase (migrated)'
FROM purchase
WHERE points_earned > 0;

-- Reconciliation: any difference between the stored balance and the credits above becomes an explicit ADJUST entry
INSERT INTO points_ledger (client_id, type, points, balance_after, reason)
SELECT c.id, 'ADJUST',
       c.points - COALESCE((SELECT SUM(l.points) FROM points_ledger l WHERE l.client_id = c.id), 0),
       c.points, 'Balance reconciliation (migration)'
FROM client c
WHERE c.points <> COALESCE((SELECT SUM(l.points) FROM points_ledger l WHERE l.client_id = c.id), 0);

-- ---- redemptions of catalog rewards (a voucher the client shows at the counter)
CREATE TABLE redemption (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    client_id BIGINT NOT NULL,
    reward_id BIGINT NOT NULL,
    establishment_id BIGINT NOT NULL,
    points_cost INT NOT NULL,
    code VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (code),
    FOREIGN KEY (client_id) REFERENCES client(id),
    FOREIGN KEY (reward_id) REFERENCES reward(id),
    FOREIGN KEY (establishment_id) REFERENCES establishment(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT chk_redemption_status CHECK (status IN ('ISSUED', 'USED'))
);
CREATE INDEX idx_redemption_client ON redemption (client_id);
CREATE INDEX idx_redemption_establishment ON redemption (establishment_id);
