-- Account lifecycle: password recovery, forced password change, establishment status/plan.
-- Valid on both PostgreSQL and H2.

-- ---- users
ALTER TABLE users ADD COLUMN must_change_password BOOLEAN DEFAULT FALSE NOT NULL;
-- Tokens issued before this moment stop working (set whenever the password changes)
ALTER TABLE users ADD COLUMN password_changed_at TIMESTAMP;

-- ---- single-use links to set a password (forgot password, or the invitation of a new user).
-- Only a SHA-256 hash of the token is stored, so a database leak does not expose usable links.
CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    type VARCHAR(20) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (token_hash),
    FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_password_token_type CHECK (type IN ('RESET', 'INVITE'))
);
CREATE INDEX idx_password_reset_token_user ON password_reset_token (user_id);

-- ---- establishment commercial status. Existing establishments keep working (ACTIVE).
ALTER TABLE establishment ADD COLUMN status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL;
ALTER TABLE establishment ADD COLUMN plan VARCHAR(100);
ALTER TABLE establishment ADD COLUMN trial_ends_at DATE;
ALTER TABLE establishment ADD CONSTRAINT chk_establishment_status CHECK (status IN ('TRIAL', 'ACTIVE', 'SUSPENDED'));
